server:
  port: 12345
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangchao
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    generate-ddl: true
    open-in-view: false
